# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
label B0 = "Friday"
label C0 = "Sunday"
label D0 = "Tuesday"
label A1 = "Body Part"
label B1 = "Day1"
label C1 = "Day2"
label D1 = "Day3"
label E1 = "VolumeWeek"
label A2 = "Chest"
let B2 = 3
let C2 = 3
let D2 = 2
let E2 = @sum(B2:D2)
label B3 = "Bench"
label C3 = "Bench"
label D3 = "Bench"
label A4 = "Triceps"
let B4 = 3
let C4 = 3
let D4 = 2
let E4 = @sum(B4:D4)
label B5 = "SkullCrush"
label C5 = "OHext"
label D5 = "Kickbacks"
label A6 = "Biceps"
let B6 = 3
let C6 = 3
let D6 = 2
let E6 = @sum(B6:D6)
label B7 = "BB Curl"
label C7 = "DB Curls"
label D7 = "pnd curl"
label A8 = "Back"
let B8 = 3
let C8 = 4
let E8 = @sum(B8:D8)
label B9 = "Pullups"
label C9 = "BB Rows"
label A10 = "Deadlifts"
let B10 = 3
let D10 = 4
let E10 = @sum(B10:D10)
label A13 = "MovDay"
let B13 = 5
let C13 = 4
let D13 = 4
label A15 = "Reps"
label A16 = "CP"
label B16 = "8-10"
label A17 = "deads"
label B17 = "5-8"
label A18 = "iso"
label B18 = "10-12"
label A19 = "Dbl Prg"
goto A12
movetosheet "Sheet1"
mark a "Sheet1" D3
mark b "Sheet1" C4
mark c "Sheet1" D4
